/* ACTS I–II — short text, map-driven */
window.CRISES_A = [
/* ───────────────────────────── 1 ───────────────────────────── */
{
  id: 1, act: 'I', code: 'SARNIA',
  title: 'The Sarnia Question',
  sub: 'A small country asks to pick a side',
  where: ['SARNIA', 'VHELM', 'ASHKARR'], look: 'SARNIA',
  arcs: [['VHELM', 'SARNIA'], ['ASHKARR', 'SARNIA']],
  setup: 'Sarnia wants to join Ashkarr\'s alliance. Vhelm has put 40,000 troops on Sarnia\'s other border and calls this a threat to its survival.',
  facts: [['Vhelm\'s real intentions', 'NOBODY KNOWS'], ['Sarnian opinion', '61% pro-Ashkarr'],
          ['The border ground', 'FLAT — easy to attack across'], ['What Ashkarr will promise', 'NOTHING IN WRITING']],
  idea: {term: 'You can count tanks. You cannot read minds.',
         def: 'Every school agrees you can measure what a country has. They disagree about whether you can know what it wants — and what you may do about not knowing.'},
  options: [
    { id: 'A', label: 'Guarantee Sarnia yourself. Send two divisions now.',
      flash: 'TWO DIVISIONS MOVE TO THE BORDER',
      aff: {off: 3, cla: 2, heg: 1}, effect: {power: 2, security: -1, legit: -1, domestic: 1, esc: 3},
      then: 'You get there in eleven hours. Vhelm does not shoot — and quietly triples its own garrison.',
      teach: {who: 'off', body: 'You never asked what Vhelm <em>wants</em>, only what it <em>could do</em>. That is offensive realism, and it is a deliberate choice: intentions are unknowable, so plan against capability. Notice the price — your power went up and your safety went down. That is the security dilemma, and Jervis is about to raise it.'} },
    { id: 'B', label: 'Say Sarnia is not vital to you. Let Ashkarr handle it.',
      flash: 'MERIDIA STANDS ASIDE',
      aff: {def: 3, off: 2, neo: 1}, effect: {power: 0, security: 1, legit: -1, domestic: -1, esc: -1},
      then: 'Ashkarr makes a promise it cannot fund. Vhelm spots the gap between you and starts poking it. Your budget has a great year.',
      teach: {who: 'def', body: 'This is passing the buck, and both Waltz and Mearsheimer say it is a great power\'s favourite move — someone else might pay. The 1930s are the warning: everyone waited for somebody else to hold the line, so nobody did.'} },
    { id: 'C', label: 'Propose a treaty: nobody garrisons Sarnia, both sides accept inspectors.',
      flash: 'INSPECTORS DEPLOY TO BOTH FRONTIERS',
      aff: {lib: 3, def: 1, con: 1}, effect: {power: -1, security: 2, legit: 3, domestic: -1, esc: -2},
      then: 'Fourteen months of talks. Vhelm signs, and squeezes a trade concession out of you. Neither side likes the deal. Both keep it.',
      teach: {who: 'lib', body: 'You did not pretend anyone had become nice — you changed what cheating costs. Inspectors supply the thing a security dilemma lacks: information. In game terms you raised the odds of a next round until cooperating paid better than defecting.'} },
    { id: 'D', label: 'Say Sarnians are our kind of people, so we defend them.',
      flash: 'MERIDIA CLAIMS A SHARED IDENTITY',
      aff: {con: 3, cla: 1, lib: 1}, effect: {power: 0, security: 0, legit: 2, domestic: 2, esc: 1},
      then: 'The speech is everywhere in a week. Two other small neighbours start calling themselves Meridian. Vhelm calls it "sentimental aggression".',
      teach: {who: 'con', body: 'You changed what the border <em>means</em> instead of what defends it — and gained standing without moving a soldier. But you have written a cheque: if being Meridian is the reason, you cannot drop Sarnia later without becoming a different country.'} },
    { id: 'E', label: 'Ask who wrote Sarnia\'s request. Refuse to fight a traders\' war.',
      flash: 'MERIDIA PUBLISHES THE PAPER TRAIL',
      aff: {cri: 3, neo: 1}, effect: {power: 0, security: 0, legit: 1, domestic: -2, esc: -1},
      then: 'It was drafted by Ashkarran grain firms chasing tariff access. Your dossier proves it, changes no troop numbers, and brings down Sarnia\'s government.',
      teach: {who: 'cri', body: 'You refused the question and asked who it served — and "Sarnia\'s national interest" turned out to have owners. That is a real gain. It is also why this school is strong at exposing whose order this is and thin on what you do at 4 a.m.'} }
  ],
  test: { from: 'def', speaker: 'Robert Jervis',
    q: 'Vhelm\'s troops are there because Vhelm is frightened of <em>you</em>. Your response frightens it more, so it arms, so you arm. Nobody wants war and the arms race happens anyway. What is this called, and what actually helps?',
    options: [
      {text: 'The security dilemma. It eases when defending is clearly different from attacking, and cheaper.', ok: true,
       why: 'Right — and the second half is the part people forget. Jervis needs two things: that others can <em>tell</em> your defences from your weapons, and that defending is the cheaper option. Walls reassure. Aircraft carriers do not.'},
      {text: 'The prisoner\'s dilemma. It eases when both sides act rationally.', ok: false,
       why: 'Close, but rational play is exactly what produces the bad outcome in a single round. And the security dilemma is the sharper case: <em>both</em> sides only want to defend, and they spiral anyway.'},
      {text: 'The Thucydides trap. It eases when the rising power accepts the rules.', ok: false,
       why: 'Different machine. That one is about growth rates crossing. Two countries of equal, unchanging strength who are both frightened will spiral perfectly well.'},
      {text: 'The balance of power. It eases once the balance settles.', ok: false,
       why: 'That names the result, not the trap. Europe in 1914 was a balance of power, and it had a ferocious arms race and a war nobody chose.'}
    ] }
},
/* ───────────────────────────── 2 ───────────────────────────── */
{
  id: 2, act: 'I', code: 'KALOS',
  title: 'The Kalos Straits',
  sub: 'Does your shield look like a sword?',
  where: ['KALOS', 'MERIDIA', 'VHELM'], look: 'KALOS',
  arcs: [['KALOS', 'MERIDIA']],
  setup: 'Most of your energy comes through the Kalos Straits. Your navy offers two plans that cost almost the same.',
  facts: [['Plan HARBOUR', 'Mines, shore guns, sensors'], ['HARBOUR range', 'USELESS 80KM OUT'],
          ['Plan LANCE', 'Two carrier groups, marines'], ['LANCE range', 'REACHES FOUR CAPITALS']],
  idea: {term: 'Attack or defend — which is cheaper, and can outsiders tell?',
         def: 'When weapons are obviously defensive and defending is cheap, you can be safe without scaring anyone. When they look the same and attacking is cheap, you get arms races. This is a rare case where you choose.'},
  options: [
    { id: 'A', label: 'Build HARBOUR. Invite Vhelm\'s attaché to watch the tests.',
      flash: 'MERIDIA BUYS A SHIELD, AND SHOWS IT',
      aff: {def: 4, lib: 1, con: 1}, effect: {power: -1, security: 3, legit: 2, domestic: -2, esc: -3},
      then: 'Vhelm cancels one of three carriers. Your shipyards fund the opposition. Three years on, a famine nearby needs a naval relief bridge and you have none.',
      teach: {who: 'def', body: 'The clever part is not that you chose defence — it is that you made the choice <em>checkable</em>. Glaser calls this reassurance. The cost is in that last sentence: a force that can only defend also cannot do any of the good things.'} },
    { id: 'B', label: 'Build LANCE. Announce nothing.',
      flash: 'CARRIER LAID DOWN AT MERIDIA',
      aff: {off: 4, heg: 2, cla: 1}, effect: {power: 3, security: 0, legit: -2, domestic: 2, esc: 3},
      then: 'Huge applause at home. Vhelm lays down four. Ashkarr, which had ignored you, opens an embassy office and starts courting Sarnia seriously.',
      teach: {who: 'off', body: 'Mearsheimer would call this cheap at the price: you cannot know if you will need long reach in 2045, and you cannot buy it in a hurry. Note the honesty of the theory — it does not promise you feel safer, only that you are stronger.'} },
    { id: 'C', label: 'Build HARBOUR and set up a shared shipping-lane authority.',
      flash: 'NINE STATES JOIN THE TRANSIT REGIME',
      aff: {lib: 4, def: 2, con: 1}, effect: {power: 0, security: 2, legit: 3, domestic: -1, esc: -2},
      then: 'Nine states join, Vhelm included, and it immediately demands the chair. The body survives two shootings and a blockade attempt. Everyone complains. Nobody leaves.',
      teach: {who: 'lib', body: 'You turned something you had to fight over into something you run jointly. Keohane\'s point is that these bodies outlive the power that built them, because they are useful. The sign it is working is not that members like it — it is that they grumble and stay.'} },
    { id: 'D', label: 'Publish both plans and let parliament decide in the open.',
      flash: 'THE COMMITTEE PICKS A BIT OF BOTH',
      aff: {neo: 4, lib: 1, cri: 1}, effect: {power: 1, security: 0, legit: 1, domestic: 3, esc: 1},
      then: 'You get one carrier, half the shore guns, and a marine base in the committee chair\'s home province. Incoherent, unkillable, and funded for twenty years.',
      teach: {who: 'neo', body: 'This is neoclassical realism: asking what the situation demands is pointless if you cannot raise the money. Coalitions must be paid, so real states build messy things. And the messy funded plan may well beat the elegant one that gets cancelled in year three.'} },
    { id: 'E', label: 'Refuse the question. Spend twenty years ending the dependence.',
      flash: 'MERIDIA REBUILDS ITS ENERGY BASE',
      aff: {cri: 3, lib: 2, con: 1}, effect: {power: 1, security: 2, legit: 1, domestic: -2, esc: -2},
      then: 'Two governments keep it, the third guts it. Dependence still falls from 60% to 31%, which turns out to be the best strategic asset you own.',
      teach: {who: 'cri', body: 'The "security problem" was really a fact about your economy, so you went after the economy. Cox would point out that your navy could not see this option, because a navy is built to answer questions about ships.'} }
  ],
  test: { from: 'off', speaker: 'John Mearsheimer',
    q: 'Say you built the reassuring force and Vhelm matched it. Twenty years pass. Vhelm now has a new government, twice the economy, and no memory of your gesture. What is my objection?',
    options: [
      {text: 'Intentions expire. Capabilities are the only thing you can plan against.', ok: true,
       why: 'That is the hinge. Offensive and defensive realists start from identical premises and split here: Mearsheimer says today\'s reassured partner has tomorrow\'s new cabinet, so intent has no shelf life and capability is all you can hold on to.'},
      {text: 'States care who gains more, so reassurance is always a loss.', ok: false,
       why: 'A real realist argument, but it is aimed at trade deals, not force posture — and it is not what the twenty-year gap is doing. The point is that the government you reassured is gone.'},
      {text: 'You cannot actually tell defensive weapons from offensive ones.', ok: false,
       why: 'That attacks the distinction itself, which is a fair fight but a different one. Grant that the distinction works perfectly today — Mearsheimer\'s clock still runs.'},
      {text: 'Treaties cannot be enforced without a dominant power.', ok: false,
       why: 'That is the realist case against international organisations, and Keohane wrote a whole book answering it. It has nothing to do with which ships you build.'}
    ] }
},
/* ───────────────────────────── 3 ───────────────────────────── */
{
  id: 3, act: 'II', code: 'GRAIN',
  title: 'The Grain Compact',
  sub: 'A deal that makes you both richer, them faster',
  where: ['VHELM', 'MERIDIA', 'TIER'], look: 'VHELM',
  arcs: [['VHELM', 'MERIDIA'], ['TIER', 'VHELM']],
  setup: 'Vhelm offers a twenty-year food and fertiliser deal. Your economists have checked it four times and agree on the numbers.',
  facts: [['You gain', '+1.4% growth a year'], ['Vhelm gains', '+2.3% growth a year'],
          ['Size gap now', 'you 1.00 : them 0.86'], ['Size gap in 20 years', 'you 1.00 : them 1.02']],
  idea: {term: 'Better off, or ahead?',
         def: 'Liberals say take any deal that leaves you better off than no deal. Realists say you also have to watch the gap, because today\'s economic lead becomes tomorrow\'s military one. Both are consistent. They advise the opposite.'},
  options: [
    { id: 'A', label: 'Sign it. Growth is growth, and trade cuts both ways.',
      flash: 'THE COMPACT IS SIGNED',
      aff: {lib: 4, con: 1}, effect: {power: 1, security: 1, legit: 2, domestic: 2, esc: -2},
      then: 'Year 8: your shops have never been fuller and two provinces now depend on Vhelmish fertiliser. Year 14: a border incident that once meant mobilisation is settled in nine days.',
      teach: {who: 'lib', body: 'Two liberal arguments at once. Being better off is the right goal — and the brutal cost of quitting is a feature, because it makes the promise believable. Trade also makes war expensive enough to stop being an option. Both objections arrive in year twenty-one.'} },
    { id: 'B', label: 'Refuse. A deal that closes the gap is a deal against you.',
      flash: 'MERIDIA WALKS AWAY',
      aff: {off: 4, heg: 2, def: 1}, effect: {power: 0, security: 1, legit: -2, domestic: -2, esc: 1},
      then: 'Your farmers are poorer for a generation. Vhelm signs with the Southern Tier instead, gets most of the growth anyway, and picks up four new friends who now vote with it.',
      teach: {who: 'off', body: 'You watched the gap rather than the gain, exactly as realists predict. But look what happened: refusing did not protect your lead, because Vhelm had somewhere else to go. That only works if you are the partner nobody can replace.'} },
    { id: 'C', label: 'Sign, but with a hard ten-year cut-off you can walk away at.',
      flash: 'A TEN-YEAR CLAUSE IS WRITTEN IN',
      aff: {def: 3, lib: 2, neo: 1}, effect: {power: 1, security: 1, legit: 1, domestic: 1, esc: -1},
      then: 'Year ten arrives. The two economies are now so tangled that leaving is unthinkable in both capitals. The clause is renewed and never mentioned again.',
      teach: {who: 'def', body: 'A sensible hedge that failed in an instructive way. You assumed the you of year ten would want what the you of year zero wanted. Ten years of trade built the people who then defended it — the escape hatch was destroyed by the very deal it was insuring.'} },
    { id: 'D', label: 'Sign it, and let the people who profit reshape your politics.',
      flash: 'AN EXPORT BLOC BEGINS TO FORM',
      aff: {neo: 3, cri: 2, lib: 1}, effect: {power: 1, security: 0, legit: 0, domestic: 3, esc: -1},
      then: 'Twelve years later a Grain Party governs. It is friendly to Vhelm, ruthless to the suppliers it undercut, and completely uninterested in your navy.',
      teach: {who: 'neo', body: 'You used foreign policy to build a domestic coalition. That is a point where neoclassical realists and Marxists agree from opposite directions: whoever controls the bargaining at home controls what "the national interest" means. Coalitions then pick their own goals.'} },
    { id: 'E', label: 'Ask who eats. Publish who wins and who pays before signing.',
      flash: 'THE DISTRIBUTION REPORT IS RELEASED',
      aff: {cri: 4, neo: 1}, effect: {power: 0, security: 0, legit: 2, domestic: -1, esc: 0},
      then: 'The gains land in two coastal provinces. The losses land on inland smallholders and on poorer suppliers abroad. You sign anyway, with compensation you underfund. The interior remembers for thirty years.',
      teach: {who: 'cri', body: '"Both countries gain" turned into transfers between regions and classes, with poorer countries quietly paying part of the bill. The point is not that trade fails to make wealth — it is that the national total is the wrong unit for asking who won.'} }
  ],
  test: { from: 'lib', speaker: 'Robert Keohane',
    q: 'Say you refused on the grounds that the gap matters. When does refusing actually protect you, rather than just making you poorer?',
    options: [
      {text: 'Only when you are the partner they cannot replace.', ok: true,
       why: 'Yes — and this is where the argument usually breaks. Watching the gap assumes a two-country world. Add a third country with similar goods and your refusal just moves the profit elsewhere while you pay the cost.'},
      {text: 'Only when it is a one-off deal with no future rounds.', ok: false,
       why: 'Right instinct, wrong target. In a one-off deal cheating is more tempting, which strengthens the case for refusing. What matters here is whether they have other options.'},
      {text: 'Only when both countries are democracies.', ok: false,
       why: 'That is machinery about whose threats are believable. It does not bear on whether refusing a trade deal protects your lead.'},
      {text: 'Always. Under anarchy, position beats prosperity.', ok: false,
       why: 'That is the strong version, and this crisis is the standard counter-example: Vhelm got its growth from the Southern Tier. "Always" also makes the claim impossible to test, which is no favour to it.'}
    ] }
},
/* ───────────────────────────── 4 ───────────────────────────── */
{
  id: 4, act: 'II', code: 'THRENE',
  title: 'Thirty Days in Threne',
  sub: 'The threat is obvious. You cannot respond.',
  where: ['THRENE', 'VHELM', 'MERIDIA'], look: 'THRENE',
  arcs: [['VHELM', 'THRENE']],
  setup: 'A Vhelm-backed faction has seized Threne\'s capital and its deep-water port. Every analyst agrees this is aimed at you. Your parliament is deadlocked and you have no emergency tax powers.',
  facts: [['Analysts agree it is a threat', 'UNANIMOUS'], ['Governing coalition', 'SPLIT 2 OF 4 PARTIES'],
          ['Emergency funding', 'NONE AVAILABLE'], ['Army ready in', '90 DAYS'], ['Politics ready in', 'UNKNOWN']],
  idea: {term: 'Seeing a threat is not the same as answering it',
         def: 'Theory says countries balance against threats. Often they just don\'t. Schweller\'s answer: split elites and weak tax powers mean a state can see a danger perfectly clearly and still fail to move.'},
  options: [
    { id: 'A', label: 'Force it through. Emergency powers, deploy, dare them to break the coalition.',
      flash: 'EMERGENCY POWERS INVOKED',
      aff: {cla: 3, off: 2, heg: 1}, effect: {power: 1, security: 1, legit: -2, domestic: -3, esc: 2},
      then: 'You deploy on day 61. The coalition falls on day 74. Your successor pulls the brigade out in its first month and spends four years litigating your decree.',
      teach: {who: 'cla', body: 'A classical realist might approve: act on the national interest and take the personal cost. But the ending is the neoclassical rebuke — you created a military fact your own state could not keep paying for.'} },
    { id: 'B', label: 'Buy the coalition first. Spend ninety days on domestic politics.',
      flash: 'SUBSIDIES, A SHIPYARD, TWO CABINET POSTS',
      aff: {neo: 4, cla: 1}, effect: {power: 1, security: 1, legit: 0, domestic: 2, esc: 1},
      then: 'It costs 11% of the defence budget in pure pork and takes 140 days. The force is smaller than planned and arrives after the port is fortified — then stays for a decade, funded.',
      teach: {who: 'neo', body: 'The neoclassical answer in full: treat your own weak finances as the real constraint and spend strategy on fixing it. Slower and smaller, in exchange for lasting. Waltz would say this is history, not theory. Schweller would say the 140 days is where policy actually happens.'} },
    { id: 'C', label: 'Skip the military. Sanctions, no recognition, port litigation.',
      flash: 'THE PORT IS PUT UNDER LEGAL SIEGE',
      aff: {lib: 3, con: 2, def: 1}, effect: {power: -1, security: 0, legit: 3, domestic: 1, esc: -2},
      then: 'Four years of paperwork. The faction is never removed and never recognised. The port runs at 40% because no insurer will touch it, and Vhelm pays for all of it forever.',
      teach: {who: 'lib', body: 'You matched your tools to what you could afford. Legal and financial instruments are slow and weak one at a time, and they add up while costing you almost nothing. The quiet machine here is insurance markets. Realists will note the enemy port is still there.'} },
    { id: 'D', label: 'Change what this is about. Make it sovereignty, not Meridia.',
      flash: 'THE THRENE PRECEDENT IS NAMED',
      aff: {con: 4, lib: 1}, effect: {power: 0, security: 0, legit: 3, domestic: 1, esc: 0},
      then: 'Within two years "the Threne precedent" is quoted by states with no interest in the region. Vhelm starts denying it intervened at all. The faction still has the port.',
      teach: {who: 'con', body: 'Name the violation, build the coalition, let it spread. The giveaway is Vhelm\'s <em>denial</em> — a country that bothers to deny something has accepted the standard it is being judged by. Whether that beats a deep-water port is exactly what Mearsheimer thinks is obvious.'} },
    { id: 'E', label: 'Ask why your state is too weak to act, and fix that.',
      flash: 'AN INQUIRY OPENS INTO WHO BLOCKED TAX REFORM',
      aff: {cri: 3, neo: 3}, effect: {power: 1, security: 0, legit: 1, domestic: -1, esc: 0},
      then: 'The inquiry names four families and two export sectors. Threne is lost meanwhile. The tax reform passes in your last month and changes what every future government can do.',
      teach: {who: 'cri', body: 'Here the critical and neoclassical schools land on the same finding — state capacity is the real variable — and disagree completely about why. For Schweller, split elites are a fact to model. For Cox, weak tax powers are exactly what the state was arranged to protect.'} }
  ],
  test: { from: 'def', speaker: 'Kenneth Waltz',
    q: 'You have spent this crisis on domestic politics. My complaint is about method. What do you give up by letting a country\'s insides into your theory?',
    options: [
      {text: 'Simplicity and prediction — with enough internal detail, any outcome can be explained afterwards.', ok: true,
       why: 'That is the charge, stated fairly. Waltz gets recurring patterns precisely by ignoring insides. Let in elite splits and leaders\' perceptions and you can fit any history, which buys reach at the cost of ever being wrong.'},
      {text: 'Nothing. Waltz\'s theory could never be tested anyway.', ok: false,
       why: 'Too quick, and it throws away the good argument. Waltz makes checkable claims: balances form, bids for dominance get punished. His whole point is that <em>adding</em> internal detail is what makes a theory unfalsifiable.'},
      {text: 'Any ability to explain foreign policy.', ok: false,
       why: 'Backwards. Waltz would happily agree his theory does not explain one country\'s foreign policy, and say that was never the job. Explaining foreign policy is what the neoclassical school wants, and it pays in simplicity.'},
      {text: 'The difference between attacking and defending.', ok: false,
       why: 'Unrelated. That is a setting inside structural realism — Jervis, Van Evera and Mearsheimer argue about it fiercely while all keeping the state sealed shut.'}
    ] }
}
];
