/* ACTS III–IV — short text, map-driven */
window.CRISES_B = [
/* ───────────────────────────── 5 ───────────────────────────── */
{
  id: 5, act: 'III', code: 'CONCORDAT',
  title: 'The Concordat Vote',
  sub: 'A new rule is being born and you hold a vote',
  where: ['CONCORDAT', 'TIER', 'VHELM'], look: 'CONCORDAT',
  arcs: [['CONCORDAT', 'MERIDIA'], ['CONCORDAT', 'VHELM'], ['CONCORDAT', 'TIER']],
  setup: 'Small states and campaign groups have forced a vote on banning cheap attack drones. You own 400,000 of them and have never misused one.',
  facts: [['Signed so far', '41 states · no great powers'], ['Your stockpile', '~400,000'],
          ['Enforcement', 'NONE'], ['Cost to replace the capability', '6× current spend']],
  idea: {term: 'How new rules spread',
         def: 'Campaigners start a standard, then it tips once enough important states join, then it stops being argued about. States follow partly because it pays and partly because of what a country like them does.'},
  options: [
    { id: 'A', label: 'Sign, and destroy the stockpile on camera.',
      flash: '400,000 UNITS DESTROYED ON CAMERA',
      aff: {con: 4, lib: 2}, effect: {power: -3, security: -2, legit: 4, domestic: -2, esc: -1},
      then: 'It tips in eight months; sixty more states sign. Your defence budget rises by a third to cover the gap. Vhelm never signs — and quietly stops using them anywhere it is being watched.',
      teach: {who: 'con', body: 'That last sentence is the whole argument: Vhelm obeying a treaty it refused to sign. Behaviour changed with no enforcement, because being seen to break the rule became costly. Note what you paid, though. This school does not claim rules are cheap, only that they cause things.'} },
    { id: 'B', label: 'Vote no, plainly, and say why.',
      flash: 'MERIDIA VOTES AGAINST',
      aff: {off: 3, def: 2, cla: 2}, effect: {power: 1, security: 1, legit: -3, domestic: 1, esc: 0},
      then: 'The treaty passes without you and stalls, having caught no great power. Two years later a mid-sized state uses the drones in a border war and quotes your speech in its defence.',
      teach: {who: 'off', body: 'More honest than signing and cheating: you neither signed nor pretended. And you were right that rules without important states tend to stall. The cost is the bit realists discount — your speech became a tool for everyone who wanted the option.'} },
    { id: 'C', label: 'Sign a version with a self-defence exemption you write yourself.',
      flash: 'MERIDIA DRAFTS THE LOOPHOLE',
      aff: {heg: 3, cla: 2, lib: 1, cri: 1}, effect: {power: 0, security: 1, legit: 1, domestic: 1, esc: 0},
      then: 'Your exemption is copied word for word by nineteen other states, Vhelm included. The treaty ends up with ninety members and bans almost nothing.',
      teach: {who: 'heg', body: 'You did not fight the rule — you <em>wrote</em> it. That is the difference between force and real dominance: rule that works because everyone adopts your framing. Ikenberry calls this a success; Cox calls the same act the thing he is warning about.'} },
    { id: 'D', label: 'Abstain, and pay for the inspection body instead.',
      flash: 'MERIDIA FUNDS THE INSPECTORATE',
      aff: {lib: 4, def: 1, con: 1}, effect: {power: 0, security: 0, legit: 2, domestic: 0, esc: -1},
      then: 'The inspectorate becomes the only trusted source of deployment data anywhere. Eleven years later it is why a much stronger treaty becomes possible.',
      teach: {who: 'lib', body: 'The bottleneck on cooperation is information, not goodwill, so you built the information. Also the most patient move on the board, and the hardest to explain to a parliament.'} },
    { id: 'E', label: 'Point out who makes these and who gets hit by them.',
      flash: 'MERIDIA NAMES THE FOUR MANUFACTURERS',
      aff: {cri: 4, con: 1}, effect: {power: -1, security: -1, legit: 3, domestic: -1, esc: 0},
      then: 'Four firms in three countries make them; they are used almost entirely on the poor edge of the world. Your speech is the decade\'s most-quoted document. The firms move two subsidiaries and carry on.',
      teach: {who: 'cri', body: 'The humanitarian framing hid a map of who manufactures and who dies, and the debate was held among the sellers. What the game will not give you is the firms actually stopping.'} }
  ],
  test: { from: 'off', speaker: 'John Mearsheimer',
    q: 'Rules, you say. Here is my test: when would I admit a rule really did something, rather than just describing what powerful states already wanted?',
    options: [
      {text: 'When a state obeys against its own interest, at real cost, with nobody enforcing it.', ok: true,
       why: 'That is the right test, and constructivists go looking for exactly it. If obeying is free, or forced, or convenient, a realist explains it without rules. Costly, unforced, inconvenient obedience is the leftover only rules explain — the chemical weapons taboo is the usual example.'},
      {text: 'When most states sign the treaty.', ok: false,
       why: 'Signing is cheap, which is why it is a weak test. Constructivists would not accept it either — they care which states join and whether behaviour changes.'},
      {text: 'When it becomes binding international law.', ok: false,
       why: 'That is a result of the rule spreading, not evidence it caused anything. Realists will say the strong write the law and exempt themselves — which is exactly what option C did.'},
      {text: 'When the dominant power enforces it.', ok: false,
       why: 'That is the one case realists can already explain, and it gives the argument away. If power is doing the work, the rule is not.'}
    ] }
},
/* ───────────────────────────── 6 ───────────────────────────── */
{
  id: 6, act: 'III', code: 'CROSSING',
  title: 'The Crossing',
  sub: 'The two growth lines meet in six years',
  where: ['ASHKARR', 'VHELM', 'MERIDIA'], look: 'ASHKARR',
  arcs: [['ASHKARR', 'VHELM'], ['ASHKARR', 'MERIDIA']],
  setup: 'Ashkarr has run the world for ninety years and now grows at 0.9%. Vhelm grows at 4.6%. Ashkarr\'s new government has started saying "closing window".',
  facts: [['Ashkarr growth', '0.9% · falling'], ['Vhelm growth', '4.6% · rising'],
          ['Vhelm passes Ashkarr in', '6 YEARS'], ['Vhelm passes you in', '11 YEARS'],
          ['Ashkarr\'s war faction', 'GROWING']],
  idea: {term: 'The dangerous one is usually the one on the way down',
         def: 'A rising country should wait — every year of growth improves its terms. A falling country faces the opposite clock. So the temptation to strike first sits with the power in decline.'},
  options: [
    { id: 'A', label: 'Stand aside. Let those two settle it and inherit what is left.',
      flash: 'MERIDIA DECLARES NEUTRALITY',
      aff: {off: 4, cla: 2, heg: 1}, effect: {power: 3, security: -2, legit: -3, domestic: 0, esc: 4},
      then: 'Nineteen months of war, worse than anyone modelled. You come out first — into a world with no shipping guarantor, no working Concordat, and two ruined powers who remember who watched.',
      teach: {who: 'off', body: 'The logical endpoint of caring only about relative power: other people\'s wars produce it cheaply. What the theory tends not to price is in the last line — the order itself was an asset, and you just spent it.'} },
    { id: 'B', label: 'Back Ashkarr now, clearly, so it stops feeling cornered.',
      flash: 'MERIDIA GUARANTEES THE OLD ORDER',
      aff: {def: 3, heg: 3, lib: 1}, effect: {power: 0, security: 2, legit: 1, domestic: -1, esc: -2},
      then: 'Ashkarr\'s war faction loses the argument and its funding. Vhelm passes Ashkarr on schedule and, finding the door unbarred, does it without firing. You are now tied to a declining patron for a generation.',
      teach: {who: 'def', body: 'The smart defensive move: you cannot stop Vhelm growing, so attack the <em>mechanism</em> instead. The theory says the danger is the cornered power, so you uncornered it. The cost is a commitment you cannot exit, made to the side that is losing.'} },
    { id: 'C', label: 'Broker a deal: give Vhelm a real say before it takes one.',
      flash: 'VOTING RIGHTS ARE RENEGOTIATED',
      aff: {lib: 4, heg: 2, con: 1}, effect: {power: 1, security: 2, legit: 3, domestic: -1, esc: -3},
      then: 'Humiliating for Ashkarr, not enough for Vhelm, and it holds. The crossing happens in year six and is reported on page nine.',
      teach: {who: 'lib', body: 'Ikenberry\'s case: a dominant power that turns its strength into rules others genuinely help write buys durability, and handovers inside a rule-based order can be renegotiated instead of fought. The weakness is that it needs a hegemon willing to be humiliated on schedule.'} },
    { id: 'D', label: 'Go after the growth rate, not the politics.',
      flash: 'THREE SUPPLY CHAINS ARE SQUEEZED',
      aff: {heg: 4, off: 2, cri: 1}, effect: {power: 1, security: 0, legit: -2, domestic: 1, esc: 2},
      then: 'Growth falls to 3.1% and the crossing slides to year fourteen. Vhelm works out what you did within eighteen months, decides the rules are a weapon, and starts building its own bloc with seven other states.',
      teach: {who: 'heg', body: 'You treated the growth gap as the thing to fix, which is what the fundamentals suggest. You also triggered the failure Gilpin predicts: once the challenger decides the order is a containment tool, it stops trying to join and starts building an alternative.'} },
    { id: 'E', label: 'Question the forecast. "Total power" is an index someone chose.',
      flash: 'MERIDIA PUBLISHES A REBUTTAL',
      aff: {con: 4, cri: 2}, effect: {power: 0, security: 1, legit: 2, domestic: -1, esc: -1},
      then: 'Your critique shows how much of "power" was an index choice and how much of "unhappy" was a decade of being excluded. Growth rates do not change. Ashkarr\'s war faction loses ground anyway, because its case rested on the forecast.',
      teach: {who: 'con', body: 'The trends are real; "the crossing" as a <em>threat</em> is an interpretation built from an index and a guess about motives. Since the war faction\'s case was that interpretation, attacking it was a real intervention. The limit: growth rates are still growth rates.'} }
  ],
  test: { from: 'heg', speaker: 'Robert Gilpin',
    q: 'One question, because nearly everyone gets the arrow backwards. Which country is more likely to start the war?',
    options: [
      {text: 'The one in decline — its window is closing, so waiting costs it something.', ok: true,
       why: 'Yes, and this is the counter-intuitive core. The rising side gains by waiting; the falling side loses by waiting. Germany in 1914 feared Russian growth; Japan in 1941 faced an embargo and an American building programme. Thucydides blamed Spartan <em>fear</em>, not Athenian ambition.'},
      {text: 'The rising challenger — it is unhappy and now strong enough.', ok: false,
       why: 'The popular reading, and the timing is backwards. Being unhappy is part of the story, but a riser with a good trend should wait: every year of 4.6% growth improves its hand.'},
      {text: 'Whichever has more offensive weapons when they draw level.', ok: false,
       why: 'That is a force-posture answer to a growth-rate question. This model runs on growth and satisfaction, not on what is in the armouries.'},
      {text: 'Neither — handovers are peaceful when institutions are strong.', ok: false,
       why: 'That is the optimistic amendment, and you may end up believing it. But it dodges the question. Gilpin asks who jumps when nothing is holding them back.'}
    ] }
},
/* ───────────────────────────── 7 ───────────────────────────── */
{
  id: 7, act: 'IV', code: 'PROBE',
  title: 'Twelve Hectares',
  sub: 'A promise is worth what breaking it costs',
  where: ['SARNIA', 'VHELM'], look: 'SARNIA',
  arcs: [['VHELM', 'SARNIA']],
  setup: 'Vhelmish irregulars have taken a customs post inside Sarnia. Twelve hectares, four buildings, nobody hurt. Vhelm calls it a police action and offers to talk calmly.',
  facts: [['Territory taken', '12 HECTARES'], ['Casualties', 'NONE'],
          ['Vhelm\'s wording', '"POLICE ACTION"'], ['Watching', '3 small allies · 2 rivals'],
          ['Public appetite for war', 'VERY LOW']],
  idea: {term: 'Making a promise believable',
         def: 'Saying you will fight is cheap. It becomes believable when backing down would cost you something — a public commitment your voters would punish you for breaking, or a tripwire you cannot switch off in time.'},
  options: [
    { id: 'A', label: 'Retake the post tonight, with your own troops, and film it.',
      flash: 'THE POST IS RETAKEN IN 40 MINUTES',
      aff: {off: 3, cla: 3, heg: 1}, effect: {power: 1, security: 0, legit: 0, domestic: 1, esc: 3},
      then: 'Forty minutes, two Vhelmish dead. No probe happens again for six years. Your parliament holds hearings on how close you came to war over twelve hectares, and the hearings are not wrong.',
      teach: {who: 'cla', body: 'Classical and offensive realists both back this — standing is a real component of power, and a tripwire only works if it actually fires. It worked, at the price the theory always understates: you accepted a live risk of great-power war over something worthless, because the object was never the point.'} },
    { id: 'B', label: 'Do not shoot. Put a permanent tripwire garrison on every crossing.',
      flash: 'TRIPWIRE GARRISONS GO IN, PERMANENTLY',
      aff: {def: 3, lib: 2, heg: 1}, effect: {power: 0, security: 2, legit: 1, domestic: -1, esc: -1},
      then: 'Vhelm withdraws before your garrison even arrives, having read the mechanism correctly. You have also permanently removed your own ability to choose not to fight.',
      teach: {who: 'def', body: 'Schelling\'s best trick: do not try to be believed, arrange things so obeying is not a decision you get to make. The cost is stated plainly — you destroyed your own flexibility, and that is exactly why it worked.'} },
    { id: 'C', label: 'Take it to arbitration.',
      flash: 'THE CASE GOES TO ARBITRATION',
      aff: {lib: 4, con: 1}, effect: {power: -1, security: 0, legit: 3, domestic: -1, esc: -3},
      then: 'Nineteen months, ruling for Sarnia, Vhelm complies partly and late. Two of your three small allies quietly open talks with Vhelm, having decided your guarantees are paperwork.',
      teach: {who: 'lib', body: 'Both halves are true. You defused a live crisis, won the ruling, and spent no blood. You also showed your allies that your promises run through a process rather than a decision — which is the one thing protecting allies cannot survive.'} },
    { id: 'D', label: 'Refuse to treat it as a test. Twelve hectares are twelve hectares.',
      flash: 'MERIDIA SHRUGS',
      aff: {def: 2, cri: 2, con: 2}, effect: {power: 0, security: 1, legit: 0, domestic: 1, esc: -2},
      then: 'Nothing happens for two years. Then a much bigger probe, somewhere that matters, by planners who cited your restraint. Whether that proved you right or wrong is still argued in your war colleges.',
      teach: {who: 'def', body: 'Mercer and Press argue reputations for toughness mostly do not transfer: opponents judge your interests in <em>this</em> crisis, and states routinely over-fight small stakes to protect an asset that is not there. The uncomfortable part is that the ambiguous ending is the honest one.'} },
    { id: 'E', label: 'Ask what the customs post actually does.',
      flash: 'IT TURNS OUT TO BE A REVENUE DISPUTE',
      aff: {cri: 4, neo: 1}, effect: {power: 0, security: 0, legit: 1, domestic: -1, esc: -1},
      then: 'It collects a tariff four export cartels wrote. Reframed as a commercial dispute, it is settled in eleven weeks by the firms involved, on terms favouring Vhelm. No soldier moves.',
      teach: {who: 'cri', body: '"Our territory is being tested" turned out to be a fight over a fee, and once named that way it became negotiable. That is a real capability. What it does not give you is an answer when the thing at stake really is sovereignty.'} }
  ],
  test: { from: 'lib', speaker: 'James Fearon',
    q: 'Why is a threat made in <em>public</em> by an elected leader more believable than the same threat made privately?',
    options: [
      {text: 'Backing down publicly would cost them at home, so the threat is expensive to abandon.', ok: true,
       why: 'Correct, and notice the shape: talk is cheap because anyone can say anything. A threat carries information only when it costs something to make or to drop. Voters supply that cost, which is why the leader\'s hands are genuinely tied.'},
      {text: 'Democracies have stronger armies, so their threats carry more weight.', ok: false,
       why: 'Strength is not the question. The puzzle is about believability given equal strength, so the answer has to be about what the threat costs.'},
      {text: 'Public threats invoke international law, which democracies must respect.', ok: false,
       why: 'That is a rules-based answer to a bargaining question. Fearon\'s machinery is entirely domestic: the leader can be thrown out for backing down.'},
      {text: 'Because elected leaders are more honest.', ok: false,
       why: 'The elegance of the argument is that it needs no honesty at all. It works with completely cynical leaders, because the punishment lands regardless of character.'}
    ] }
},
/* ───────────────────────────── 8 ───────────────────────────── */
{
  id: 8, act: 'IV', code: 'SETTLEMENT',
  title: 'The Settlement',
  sub: 'You are writing the rules. Someone has to live in them.',
  where: ['CONCORDAT', 'MERIDIA', 'ASHKARR', 'VHELM', 'TIER'], look: 'CONCORDAT',
  arcs: [['CONCORDAT', 'ASHKARR'], ['CONCORDAT', 'VHELM'], ['CONCORDAT', 'TIER'], ['CONCORDAT', 'THRENE']],
  setup: 'It is over. Ashkarr has conceded, Vhelm has been stopped short, and you are at the head of the table. Fifty-four states are in the room. A hundred and twelve are not.',
  facts: [['Your position', 'FIRST · and unstable'], ['How long this lasts', '18–36 MONTHS'],
          ['In the room', '54 STATES'], ['Not in the room', '112 STATES']],
  idea: {term: 'Every peace conference is a theory made real',
         def: 'Vienna 1815 was careful balance between great powers. Versailles 1919 mixed high principle with punishment and got the worst of both. 1945 built rules on top of obvious American dominance. Each option below has a real ancestor.'},
  options: [
    { id: 'A', label: 'A deliberate balance. Five powers, no boss, skilled diplomats.',
      flash: 'THE CONCERT OF FIVE POWERS',
      aff: {cla: 4, def: 2}, effect: {power: 0, security: 2, legit: 1, domestic: 0, esc: -1},
      then: 'Forty years of peace between the great powers, requiring a generation of unusually skilled and unusually cynical diplomats. It also freezes every grievance inside those countries until they all arrive at once.',
      teach: {who: 'cla', body: 'This is the Concert of Europe. Classical realism is proved right by the first half and indicted by the second: careful statecraft really does buy decades of peace, and it does so by treating everyone\'s domestic hopes as noise. 1848 was the bill.'} },
    { id: 'B', label: 'Rules on top of your own dominance — rules that bind you too.',
      flash: 'A RULE-BASED ORDER IS FOUNDED',
      aff: {lib: 4, heg: 3}, effect: {power: 1, security: 2, legit: 3, domestic: 0, esc: -2},
      then: 'It outlasts your dominance by decades, which was the point. It also produces a permanent argument about whether the rules apply to you, and in the cases that matter the answer is mostly no.',
      teach: {who: 'lib', body: 'Accept limits on yourself, and others join willingly — the order gets sticky enough to survive your decline. Only this school explains the survival. Cox is behind you pointing at the last sentence: an order that binds everyone except its author is dominance working properly.'} },
    { id: 'C', label: 'Take everything while the window is open. Rules are temporary.',
      flash: 'BASES, DEALS, AND A FREE HAND',
      aff: {off: 4, heg: 2}, effect: {power: 3, security: -1, legit: -3, domestic: 1, esc: 2},
      then: 'For twenty years you are clearly first and clearly alone. The coalition forms in year twenty-three, as the theory said, and includes two states you thought were allies.',
      teach: {who: 'off', body: 'Its own family says this is a mistake. Waltz\'s prediction is that last sentence: unbalanced power summons a coalition, so bids for dominance defeat themselves even when they succeed. This is the sharpest quarrel inside realism.'} },
    { id: 'D', label: 'Build it on who everyone has become, so war stops being imaginable.',
      flash: 'FOURTEEN STATES JOIN A SECURITY COMMUNITY',
      aff: {con: 4, lib: 2}, effect: {power: -1, security: 3, legit: 4, domestic: -1, esc: -3},
      then: 'Among the fourteen who fully join, war stops being planned for at all — not deterred, not unlikely, simply absent from the staff colleges. Outside that line, the line itself becomes the new organising fact of world politics.',
      teach: {who: 'con', body: 'Western Europe after 1950 is why this school cannot be dismissed: those states did not merely stop fighting, they stopped preparing to. The honest cost is the second sentence — creating an inside creates an outside.'} },
    { id: 'E', label: 'Refuse to settle among the 54. Put debt and technology on the table.',
      flash: 'THE AGENDA IS TORN UP',
      aff: {cri: 4, con: 2}, effect: {power: -2, security: 1, legit: 4, domestic: -2, esc: -1},
      then: 'You get a fraction of it — a debt facility, three technology mandates, price floors. That fraction moves more human welfare than every security clause combined, and is dismantled over the next twenty years by the states that signed it.',
      teach: {who: 'cri', body: 'The security map was never the main event, and the 54 in the room were the mechanism keeping the 112 outside. The real ancestor is the New International Economic Order of the 1970s, including the ending.'} }
  ],
  test: { from: 'cri', speaker: 'Robert Cox',
    q: 'Last question, and it is about you rather than Meridia. What did I mean by "theory is always for someone, and for some purpose"?',
    options: [
      {text: 'Every framework has a standpoint: what counts as a problem, an actor and a solution is already a choice.', ok: true,
       why: 'That is it, and it is worth taking seriously even if you reject the Marxism attached. Cox separates theory that asks how to run the current order better from theory that asks how it got here. This game had a standpoint too: it made you a state and handed you a globe.'},
      {text: 'All theories are equally valid, so pick whichever suits you.', ok: false,
       why: 'Not relativism. Cox thinks he is right and others wrong. Saying a framework has a standpoint is not saying every standpoint is as good — his claim is that some frameworks systematically hide things.'},
      {text: 'Theories should be judged by whether they help policymakers.', ok: false,
       why: 'That is exactly the position he names and criticises. Being useful to the current order\'s managers is the symptom he is diagnosing, not his standard of value.'},
      {text: 'Material interests always determine ideas.', ok: false,
       why: 'Cruder than Cox. His Gramscian side is precisely about ideas doing work on their own — rule operating through consent and common sense, not only through money and force.'}
    ] }
}
];
